# These are supported funding model platforms

github: [toxi22]
patreon: romanpavlovsky
ko_fi: romanpavlovsky
custom: ['liqpay.ua/ru/checkout/romanpavlovsky', 'send.monobank.ua/hfFqfqyVm','paypal.com/donate/?hosted_button_id=2VFW2WBPWB88L']
#Bitcoin: 33d133tnqEuPztCRoHsncnRQdXuo5eJ6xf
#Ethereum: 0x36fDE4F5508E13396247eBe6384509d300Aa4f93
